P8105 HW6: am4656
================
Aaron Mittel
2022-12-01

# Problem 1

The density plots below indicates the distribution of 5000-fold
bootstrapped sample r-squared and the log of the quantity
intercept\*slope of `tmin` within a simple linear regression estimating
the influence of `tmin` on `tmax`.
<img src="p8105_hw6_am4656_files/figure-gfm/boostrapping estimates-1.png" width="90%" />

Values of both of these estimates appear to be normally distributed in
this 5000-fold bootstrapped sample.

| ci_lower_r.squared | ci_upper_r.squared | ci_lower_log_int_b1 | ci_upper_log_int_b1 |
|-------------------:|-------------------:|--------------------:|--------------------:|
|              0.893 |              0.928 |               1.966 |               2.059 |

-   The 95% confidence interval of r-squared for this sample is (0.894,
    0.927).
-   The 95% confidence interval of ln(intercept \* beta1) is (1.966,
    2.059).
-   These values are reflected in the plots above.

# Problem 2

This problem examines data gathered by the *Washington Post* pertaining
to homicides in 50 large U.S. cities.

*Entries with missing data have been removed.*

## Baltimore, MD

In the city of Baltimore, MD, we can use logistic regression to estimate
the influence of victims’ age, gender (male vs female), and race (white
vs black) on the probability of a homicide being closed.

| term             | estimate | std.error | statistic | p.value | conf.low | conf.high |
|:-----------------|---------:|----------:|----------:|--------:|---------:|----------:|
| (Intercept)      |    1.942 |     0.174 |     3.804 |    0.00 |    1.383 |     2.744 |
| victim_age       |    0.995 |     0.003 |    -1.599 |    0.11 |    0.988 |     1.001 |
| victim_sexMale   |    0.355 |     0.143 |    -7.264 |    0.00 |    0.267 |     0.468 |
| victim_raceWhite |    2.459 |     0.180 |     4.990 |    0.00 |    1.733 |     3.519 |

The odds of solving homicides for male victims are **0.355 times (95%
CI: 0.267, 0.468)** the odds of solving homicides for female victims in
Baltimore, MD, keeping all other variables fixed, at a 5% level of
significance.

## All remaining cities in *Washington Post* dataset.

The plot below demonstrates the odds of homicide case closure (closed by
arrest or closed without arrest) in several major cities in the United
States. The error bar indicates the upper and lower bounds of the 95%
confidence interval for each estimated odds ratio.

<img src="p8105_hw6_am4656_files/figure-gfm/all cities-1.png" width="90%" />

In general, homicides of male victims have lower odds of case closure
than those of female victims. Exceptions in this data include Fresno,
CA, Stockon, CA, and Minneapolis, MN, in which male and female victim’s
case closure odds are comparable. However, the confidence interval of
these 3 cities’ estimates are relatively wide compared to the rest of
the cities in the dataset.

# Problem 3

This problem uses data from a dataset of 4000 infants and evaluates
predictors of low birthweight. Several predictors, `babysex`, `frace`,
`malform`, and `mrace` are labeled as numeric entries in the original
data and have been mutated into categorical/factor variables for further
analysis. There is not a substantial amount of missing data though
`pnumlbw` and `pnumsga` are “0” across all entries.

Low birth weight is defined as a birth weight less than 2500 grams
according to the World Health Organization
(<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5710991/#b0005>). Thus,
we will mutate the dataframe to create a binary outcome of
`low_birth_wt` = 1 if birth weight is \< 2500 g and = 0 if birth weight
is greater than or equal to 2500 g.

| low_birth_wt | count |
|-------------:|------:|
|            0 |  3897 |
|            1 |   445 |

## Hypothetical Model

Hypothetically, predictors which may lead to or be protective against
low birth weight include: family monthly income (`fincome`), gestational
age in weeks (`gaweeks`), presence of malformations that could affect
weight (`malform`), mother’s age at delivery (`momage`), mother’s
pre-pregnancy BMI (`ppbmi`), average number of cigarettes smoked per day
during pregnancy (`smoken`).

These are explored with a logistic regression model.

| term        | estimate | std.error | statistic | p.value | conf.low | conf.high |
|:------------|---------:|----------:|----------:|--------:|---------:|----------:|
| (Intercept) |    10.64 |      0.75 |     14.17 |    0.00 |     9.19 |     12.14 |
| fincome     |     0.00 |      0.00 |     -1.92 |    0.05 |    -0.01 |      0.00 |
| gaweeks     |    -0.28 |      0.02 |    -17.68 |    0.00 |    -0.31 |     -0.25 |
| malform1    |    -0.21 |      0.98 |     -0.21 |    0.83 |    -2.54 |      1.42 |
| momage      |    -0.03 |      0.02 |     -1.80 |    0.07 |    -0.06 |      0.00 |
| ppbmi       |    -0.07 |      0.02 |     -3.52 |    0.00 |    -0.11 |     -0.03 |
| smoken      |     0.03 |      0.01 |      5.04 |    0.00 |     0.02 |      0.05 |

<img src="p8105_hw6_am4656_files/figure-gfm/hypothetical glm-1.png" width="90%" />

There are some obvious issues with this model which warrant further
investigation.

We can compare this hypothetical model to others which may be superior.

## Comparison Models

The first comparison model uses length at birth (`blength`) and
gestational age (`gaweeks`) as predictors.

| term        |     estimate | std.error | statistic | p.value |     conf.low |    conf.high |
|:------------|-------------:|----------:|----------:|--------:|-------------:|-------------:|
| (Intercept) | 3.733902e+19 |      1.97 |     22.85 |       0 | 8.701046e+17 | 1.992522e+21 |
| blength     | 4.200000e-01 |      0.04 |    -21.55 |       0 | 3.900000e-01 | 4.500000e-01 |
| gaweeks     | 8.700000e-01 |      0.02 |     -7.48 |       0 | 8.300000e-01 | 9.000000e-01 |

The second comparison model uses head circumference (`bhead`), length
(`blength`), sex (`babysex`), and interactions between these variables
as predictors.

| term                   |      estimate | std.error | statistic | p.value |      conf.low |     conf.high |
|:-----------------------|--------------:|----------:|----------:|--------:|--------------:|--------------:|
| (Intercept)            | 1.410498e+152 |     55.20 |      6.35 |       0 | 1.155306e+100 | 2.785845e+197 |
| bhead                  |  0.000000e+00 |      1.64 |     -6.03 |       0 |  0.000000e+00 |  0.000000e+00 |
| blength                |  0.000000e+00 |      1.15 |     -5.70 |       0 |  0.000000e+00 |  2.000000e-02 |
| babysex2               |  0.000000e+00 |     87.73 |     -4.67 |       0 |  0.000000e+00 |  0.000000e+00 |
| bhead:blength          |  1.200000e+00 |      0.03 |      5.33 |       0 |  1.110000e+00 |  1.280000e+00 |
| bhead:babysex2         |  3.185410e+05 |      2.70 |      4.70 |       0 |  1.073480e+03 |  2.087648e+07 |
| blength:babysex2       |  4.814400e+03 |      1.84 |      4.61 |       0 |  1.008400e+02 |  8.749445e+04 |
| bhead:blength:babysex2 |  7.700000e-01 |      0.06 |     -4.65 |       0 |  7.000000e-01 |  8.700000e-01 |

### Cross-Validation of Models

<img src="p8105_hw6_am4656_files/figure-gfm/cross validation-1.png" width="90%" />

The hypothetical model has a substantially lower RMSE than that of the
other tested models with respect to accuracy of predicting low birth
weight among this data.
